### PR TITLE
buffer fixes for gcc

### PR DESCRIPTION
**Pull request by carmichaelong**
@tgeijten Mainly templatization fixes that prevent gcc from compiling. Also need to use c++14 option for gcc now (requires 4.9 minimum).

### CODE REVIEW

**Comment by chrisdembia** [comment]
Using c++14 could be problematic. Different c++ standards are not ABI-compatible, meaning OpenSim likely needs to be compiled as c++14 as well. We have not yet decided to move to c++14. We haven't ruled it out, but the choice should not be made lightly. What relies on c++14?

**Comment by chrisdembia** [comment]
It is extremely likely that OpenSim can be compiled as c++14, and perhaps we should at least make it an option for OpenSim 4.0. But I think it is likely that we want OpenSim 4.0 to ship as c++11.

**Comment by carmichaelong** [comment]
Thanks for the heads up. Seems like only one line would need it (https://github.com/tgeijten/flut/blob/master/flut/math/regular_piecewise_linear_function.hpp#L20) for `std::make_unique`

**Comment by chrisdembia** [comment]
Cool; thanks for the heads up.

It would be good to set up CI so that we can catch such issues.

**Comment by carmichaelong** [comment]
Found this as a resource for a possible way of dealing with it with c++11: 
http://stackoverflow.com/questions/7038357/make-unique-and-perfect-forwarding

Tried implementing it in the flut namespace for non-c++14 compilers. Unfortunately there's an error when compiling:

```
/home/ongcf/repos/flut/source/test/../flut/make_unique_wrapper.hpp:23:67: error: invalid use of array with unspecified bounds
             return std::unique_ptr<T>(new T(std::forward<U>(u)...))
```

**Comment by tgeijten** [comment]
Thanks -- not sure why you have to use the `this->` before `current_channel()` though? There was an erroneous `bufinf` there that had to be removed, but I don't understand the `this`

**Comment by chrisdembia** [comment]
I think it's because the symbol is dependent on the template arguments. MSVC is pretty bad with following the standard with regard to templates.

http://stackoverflow.com/questions/37599877/why-an-incomplete-type-is-detected-in-clang-inside-a-template-method

There is a great LLVM blog post about it two-step template instantiation, but I can't seem to find it right now.

BTW MSVC 2015 now provides a clang front end to its compiler. You could use that to catch bugs.

**Comment by tgeijten** [comment]
Concerning the std::make_unique(): there's no need to actually use that, I replaced it by using standard initialization through the std::unique_ptr constructor.

**Comment by tgeijten** [comment]
@chrisdembia or @carmichaelong: can you show the GCC error if you remove the `'this->`? I'm curious to find out what's going on.

@chrisdembia: Thanks for the info, I'll look into VS2015 when I have the chance. Are you using that for already for OpenSim 4?

Concerning the build settings: VS2013 supports some C++14 extensions, while several C++11 extensions are not included. The extensions can only be enabled / disabled all at once. For building on Windows, it would make more sense to support specific compiler versions instead language extensions. Would that also make sense with Clang / GCC (my guess is no :smile:)?

**Comment by chrisdembia** [comment]
> @chrisdembia or @carmichaelong: can you show the GCC error if you remove the 'this->? I'm curious to find out what's going on.

I found the blog post on two-phase name lookup http://blog.llvm.org/2009/12/dreaded-two-phase-name-lookup.html

> @chrisdembia: Thanks for the info, I'll look into VS2015 when I have the chance. Are you using that for already for OpenSim 4?

Yes; 4.0 does not support VS2013.

> Would that also make sense with Clang / GCC (my guess is no 😄)?

I think no. Part of the reason is ABI compatibility.  For example, I think gcc 4.3 and 4.4 are ABI compatible, so long as you are using c++11. One reason why it makes more sense to support a given version of MSVC is that each version of MSVC is not binary compatible with the others (that's my understanding at least).

Interestingly, MSVC is moving towards flags for different c++ standards: https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/

**Comment by tgeijten** [comment]
> I found the blog post on two-phase name lookup http://blog.llvm.org/2009/12/dreaded-two-phase-name-lookup.html

Thanks for the link, @chrisdembia! That's an excellent post explaining an issue I was not aware of.

Furthermore, I'll refrain from using any C++14 features for now, at least until we move to VS2015 for SCONE.

**Comment by chrisdembia** [comment]
Much appreciated!

**Pull request merged**
